//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMsLogisctics.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ExtraFile = new HashSet<ExtraFile>();
            this.Rule = new HashSet<Rule>();
            this.Rule1 = new HashSet<Rule>();
        }
    
        public int Id { get; set; }
        public string Comment { get; set; }
        public string Code { get; set; }
        public int StatusId { get; set; }
        public int ClientId { get; set; }
        public int StartLocation { get; set; }
        public int EndLocation { get; set; }
        public Nullable<int> CourierId { get; set; }
        public Nullable<decimal> CourierRate { get; set; }
        public Nullable<decimal> ClientRate { get; set; }
        public int ManagerId { get; set; }
        public int OrderTypeId { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public Nullable<System.TimeSpan> TimeOfDelivery { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Courier Courier { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual OrderType OrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExtraFile> ExtraFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rule> Rule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rule> Rule1 { get; set; }
    }
}
